import {
  CREATE_BEVERAGE_FORM,
  CREATE_CATEGORY,
  CREATE_PARTNER,
  DELETE_BEVERAGE,
  DELETE_CATEGORY,
  EDIT_BEVERAGE_FORM,
  EDIT_CATEGORY,
} from './forms.constants';
import { NO_INDEX_PAGE } from './seo.constants';

export {
  CREATE_BEVERAGE_FORM,
  CREATE_CATEGORY,
  CREATE_PARTNER,
  DELETE_BEVERAGE,
  DELETE_CATEGORY,
  EDIT_BEVERAGE_FORM,
  EDIT_CATEGORY,
  NO_INDEX_PAGE,
};
